local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fs', builtin.lsp_document_symbols, { desc = 'search symbols in file' })
vim.keymap.set('n', '<leader>gr', builtin.lsp_references)
